### ISSUE TITLE
前端一直无法连接

### ISSUE THREAD

**Issue by forliuyifei** [QingxuMo/Aria2-Termux#1]
已经成功安装并启动，可是不论用哪个前端页面都无法启动，端口和RPC密钥都没填错。
还有哪里不对吗？连接协议选哪个？

**Comment by QingxuMo** [comment]
建议按如下顺序排查：

- 如果在同设备运行则检查 IP 地址是否 127.0.0.1 或内网 IP 地址（可以在手机设置和脚本「查看 配置」选项查看）
- 如果是网页前端则检查网页连接是否使用的是 HTTP 而不是 HTTPS（HTTPS连接需要专门配置证书，脚本没有对此一键配置）
- 如果完全按照脚本一键配置请检查 Aria2 RPC 协议是否为 WebSocket（不是「 WebSocket 安全」）

正常来说你只需要复制脚本中「查看 配置」中 AriaNg 链接，然后再浏览器打开链接就可以连接了。

如果问题还是没有解决，请提供相关截图（如前端 RPC 设置）

**Comment by QingxuMo** [comment]
已逾三天无后续回复，暂关闭该 issue
