### ISSUE TITLE
请问能不能加个开机自启的配置？

### ISSUE THREAD

**Issue by forliuyifei** [QingxuMo/Aria2-Termux#2]
做人帮到底嘛😂

**Comment by QingxuMo** [comment]
添加相关代码当然是可以的，原项目 [aria2.sh](https://github.com/P3TERX/aria2.sh) 本来就支持开机自启（虽然无法套用代码到 Termux 上）。

但问题是 Termux 原生不支持……
也不能说不支持，只是官方相关插件需要收费……
虽然可以通过 Magisk 模块实现相关功能，但是我觉得既麻烦又鸡肋，所以索性把这个功能砍掉了。

如果真的有相关需求的话，麻烦稍微详细一点描述你的需求的应用场景，我可以参考一下然后添加相关功能。

**Comment by forliuyifei** [comment]
> 添加相关代码当然是可以的，原项目 [aria2.sh](https://github.com/P3TERX/aria2.sh) 本来就支持开机自启（虽然无法套用代码到 Termux 上）。
> 
> 但问题是 Termux 原生不支持……
> 也不能说不支持，只是官方相关插件需要收费……
> 虽然可以通过 Magisk 模块实现相关功能，但是我觉得既麻烦又鸡肋，所以索性把这个功能砍掉了。
> 
> 如果真的有相关需求的话，麻烦稍微详细一点描述你的需求的应用场景，我可以参考一下然后添加相关功能。

那算了吧，徒增功耗。
我虽然有个备用机可能用得上，但无奈学校的校园网限制设备，用vpn热点强行连接多台设备的话倒是能玩，但限制上网时间段又是个问题 😅

**Comment by QingxuMo** [comment]
最新版本已添加 Aria2 开机自启动，请通过脚本内置的更新功能更新脚本并重新安装 Aria2。
