### ISSUE TITLE
日志无法关闭

### ISSUE THREAD

**Issue by forliuyifei** [QingxuMo/Aria2-Termux#3]
quiet=true
它依然在后台打印日志，很快就生成5MB的log文件。

**Comment by QingxuMo** [comment]
如果我没搞错的话，quiet 的配置应该是禁止在**控制台**输出日志，即，不在终端显示日志。

这个配置对于本脚本没有任何意义，因为脚本启动命令里面就加了 -D 参数。

如果你是想不输出日志文件，正确的做法应该是把配置文件中 `log=$HOME/.aria2/aria2.log` 这行（默认 330 行）注释掉或删掉。

**Comment by forliuyifei** [comment]
> 如果我没搞错的话，quiet 的配置应该是禁止在**控制台**输出日志，即，不在终端显示日志。
> 
> 这个配置对于本脚本没有任何意义，因为脚本启动命令里面就加了 -D 参数。
> 
> 如果你是想不输出日志文件，正确的做法应该是把配置文件中 `log=$HOME/.aria2/aria2.log` 这行（默认 330 行）注释掉或删掉。

好的谢谢，其实我还想直接设置日志文件的权限为不可写入，不知道会不会有什么损坏

**Comment by QingxuMo** [comment]
不会有任何问题，日志是否开启不会影响 Aria2 运行状态。
